//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 06:51:44 PM CST 
//


package haflow.util.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for erPropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="erPropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jarPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inputPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outputPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="confPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "erPropertiesType", propOrder = {
    "jarPath",
    "inputPath",
    "outputPath",
    "confPath"
})
public class ErPropertiesType {

    @XmlElement(required = true)
    protected String jarPath;
    @XmlElement(required = true)
    protected String inputPath;
    @XmlElement(required = true)
    protected String outputPath;
    @XmlElement(required = true)
    protected String confPath;

    /**
     * Gets the value of the jarPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJarPath() {
        return jarPath;
    }

    /**
     * Sets the value of the jarPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJarPath(String value) {
        this.jarPath = value;
    }

    /**
     * Gets the value of the inputPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputPath() {
        return inputPath;
    }

    /**
     * Sets the value of the inputPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputPath(String value) {
        this.inputPath = value;
    }

    /**
     * Gets the value of the outputPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputPath() {
        return outputPath;
    }

    /**
     * Sets the value of the outputPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputPath(String value) {
        this.outputPath = value;
    }

    /**
     * Gets the value of the confPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfPath() {
        return confPath;
    }

    /**
     * Sets the value of the confPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfPath(String value) {
        this.confPath = value;
    }

}
