//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 06:51:44 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.xml.util.haflow", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package haflow.util.xml;
